### PR TITLE
chore(readme): Update the React 18 upgrade docs

### PR DESCRIPTION
**Pull request by lukaselmer**
**What**:

Update the React 18 upgrade docs

**Why**:

To make it easier to upgrade to React 18

**How**:

To document what the developer can do to upgrade to React 18

**Checklist**:

- [x] Documentation updated
- [x] Tests
- [x] Ready to be merged
- [x] Added myself to contributors table

I tested it manually on my React project

### CODE REVIEW

**Comment by joshuaellis** [comment]
I personally find that this to be confusing & a little superfluous... I think the current description is fine and we probably don't want to inflate the docs further.

**Comment by lukaselmer** [comment]
> I personally find that this to be confusing & a little superfluous... I think the current description is fine and we probably don't want to inflate the docs further.

I would have helped me. And it seems I'm not the first it would have helped https://github.com/testing-library/react-hooks-testing-library/issues/832 https://github.com/testing-library/react-hooks-testing-library/issues/826. But if you think it doesn't help others then feel free to close it.

**Comment by mindplay-dk** [comment]
I spent almost a full day pulling my hair out, as all the tests broke after upgrading - error messages, as always, unhelpful.

This may be totally obvious to people who've been working with testing-library for a while - I just dropped into a project and was asked to upgrade react to 18, and I've never used testing-library, so I don't have that context.

I had to read through numerous long issues, to finally find the explanation at the end of a *long* issue thread, pointing to this PR.

There's no reason for anyone else to go through that pain - I suggest you get this merged right away.

**Comment by lukaselmer** [comment]
> I spent almost a full day pulling my hair out, as all the tests broke after upgrading - error messages, as always, unhelpful.
> 
> This may be totally obvious to people who've been working with testing-library for a while - I just dropped into a project and was asked to upgrade react to 18, and I've never used testing-library, so I don't have that context.
> 
> I had to read through numerous long issues, to finally find the explanation at the end of a _long_ issue thread, pointing to this PR.
> 
> There's no reason for anyone else to go through that pain - I suggest you get this merged right away.

Couldn't agree more :)

**Pull request merged**
